# Generated by Django 5.0.7 on 2024-07-29 14:27

import cloudinary.models
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_filter', models.CharField(choices=[('NONE', 'None'), ('GRAYSCALE', 'Grayscale'), ('SEPIA', 'Sepia'), ('NEGATIVE', 'Negative'), ('BRIGHTNESS', 'Brightness'), ('CONTRAST', 'Contrast'), ('SATURATION', 'Saturation'), ('HUE_ROTATE', 'Hue Rotate'), ('BLUR', 'Blur'), ('SHARPEN', 'Sharpen'), ('VINTAGE', 'Vintage'), ('VIGNETTE', 'Vignette'), ('CROSS_PROCESS', 'Cross Process'), ('HDR', 'HDR'), ('EDGE_DETECT', 'Edge Detect'), ('EMBOSS', 'Emboss'), ('SOLARIZE', 'Solarize'), ('POSTERIZE', 'Posterize'), ('PIXELATE', 'Pixelate'), ('CARTOON', 'Cartoon'), ('DUOTONE', 'Duotone')], default='NONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
