# Generated by Django 5.0.7 on 2024-07-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('NONE', 'None'), ('GRAYSCALE', 'Grayscale'), ('SEPIA', 'Sepia'), ('NEGATIVE', 'Negative'), ('BRIGHTNESS', 'Brightness'), ('CONTRAST', 'Contrast')], default='NONE', max_length=20),
        ),
    ]
