# Generated by Django 5.0.7 on 2024-07-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('NONE', 'None'), ('GRAYSCALE', 'Grayscale'), ('SEPIA', 'Sepia'), ('NEGATIVE', 'Negative'), ('BRIGHTNESS', 'Brightness'), ('CONTRAST', 'Contrast'), ('SATURATION', 'Saturation'), ('HUE_ROTATE', 'Hue Rotate'), ('BLUR', 'Blur'), ('SHARPEN', 'Sharpen'), ('VINTAGE', 'Vintage'), ('VIGNETTE', 'Vignette'), ('CROSS_PROCESS', 'Cross Process'), ('HDR', 'HDR'), ('EDGE_DETECT', 'Edge Detect'), ('EMBOSS', 'Emboss'), ('SOLARIZE', 'Solarize'), ('POSTERIZE', 'Posterize'), ('PIXELATE', 'Pixelate'), ('CARTOON', 'Cartoon'), ('DUOTONE', 'Duotone')], default='NONE', max_length=20),
        ),
    ]
