# Generated by Django 5.1 on 2024-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
    ]
