# Generated by Django 5.0.7 on 2024-07-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movie_genre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_music_genre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_sport',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='FavoriteMovieGenre',
        ),
        migrations.DeleteModel(
            name='FavoriteMusicGenre',
        ),
        migrations.DeleteModel(
            name='FavoriteSport',
        ),
    ]
