# Generated by Django 5.0.7 on 2024-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_favorite_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/nobody.webp', upload_to='images/'),
        ),
    ]
