# Generated by Django 5.0.7 on 2024-07-21 19:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/nobody_ceyo72', max_length=255, verbose_name='image'),
        ),
    ]
