# Generated by Django 5.0.7 on 2024-07-16 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
