# Generated by Django 5.0.7 on 2024-07-16 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_user_comment_owner'),
        ('likes', '0001_initial'),
        ('posts', '0002_remove_post_excerpt_remove_post_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'post', 'comment')},
        ),
    ]
