# Generated by Django 5.0.7 on 2024-07-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_like_unique_like_post_like_unique_like_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_post',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_comment',
        ),
    ]
