# Generated by Django 5.0.7 on 2024-07-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_reported_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='owner',
        ),
    ]
