# Generated by Django 5.0.7 on 2024-07-29 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follower',
            index=models.Index(fields=['follower', 'followed'], name='followers_f_followe_bf8f6f_idx'),
        ),
    ]
