# Generated by Django 5.0.7 on 2024-07-29 19:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_follower_followers_f_followe_bf8f6f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follower',
            name='followers_f_followe_bf8f6f_idx',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed')},
        ),
    ]
