# Generated by Django 5.0.7 on 2024-07-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_follower_unique_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
    ]
