# Generated by Django 5.0.7 on 2024-07-30 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_alter_follower_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at'], 'verbose_name': 'Follower Relationship', 'verbose_name_plural': 'Follower Relationships'},
        ),
        migrations.RemoveConstraint(
            model_name='follower',
            name='unique_follow',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='followed',
            new_name='followed_user',
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('owner', 'followed_user'), name='unique_follow'),
        ),
    ]
