# Generated by Django 5.0.7 on 2024-07-30 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0006_alter_follower_options_remove_follower_unique_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follower',
            name='unique_follow',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='owner',
            new_name='follower',
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('follower', 'followed_user'), name='unique_follow'),
        ),
    ]
